In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
df1=pd.read_csv("/content/drive/MyDrive/WCRC2023/데이터/로우 데이터/AWS_DD_2023.csv", encoding='euc-kr')
meta2=pd.read_csv("/content/drive/MyDrive/WCRC2023/데이터/로우 데이터/META_관측지점정보.csv", encoding='euc-kr')

In [ ]:
df1

,지점,지점명,일시,평균기온(°C),최저기온(°C),최저기온 시각(hhmi),최고기온(°C),최고기온 시각(hhmi),일강수량(mm),최대 순간 풍속(m/s),최대 순간풍속 시각(hhmi),평균 풍속(m/s),최대 순간 풍속 풍향(deg)
0,116,관악(레),2023-10-04,14.9,11.0,2352.0,19.2,1329.0,14.0,18.8,2356.0,3.2,334.7
1,116,관악(레),2023-10-05,10.2,7.2,710.0,14.0,1458.0,0.0,19.7,11.0,6.3,326.3
2,116,관악(레),2023-10-06,12.4,8.7,450.0,16.1,1527.0,0.0,10.9,208.0,3.9,334.7
3,116,관악(레),2023-10-07,13.6,11.5,710.0,16.3,1556.0,0.0,7.8,900.0,2.9,109.7
4,116,관악(레),2023-10-08,13.1,12.1,403.0,14.8,1458.0,0.0,8.5,138.0,3.3,115.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1694,967,도리도,2023-10-28,15.6,13.4,557.0,19.3,1238.0,0.0,6.7,24.0,1.1,284.4
1695,967,도리도,2023-10-29,15.0,12.0,715.0,19.6,1409.0,0.0,8.9,647.0,2.9,110.8
1696,967,도리도,2023-10-30,15.6,12.2,759.0,21.0,1231.0,0.0,5.1,746.0,2.1,95.5
1697,967,도리도,2023-10-31,15.4,12.7,910.0,18.0,1629.0,0.0,8.4,1633.0,3.5,238.8
1698,967,도리도,2023-11-01,18.8,17.0,31.0,20.4,1335.0,0.0,12.6,1427.0,5.2,222.7

In [ ]:
meta2

,지점,시작일,종료일,지점명,지점주소,관리관서,위도,경도,노장해발고도(m),기압계(관측장비지상높이(m)),기온계(관측장비지상높이(m)),풍속계(관측장비지상높이(m)),강우계(관측장비지상높이(m))
0,3,1900-01-01,NaN,선봉,NaN,NaN,42.3167,130.4000,3.0,NaN,NaN,NaN,NaN
1,5,1900-01-01,NaN,삼지연,NaN,NaN,41.8167,128.3167,1386.0,NaN,NaN,NaN,NaN
2,8,1900-01-01,NaN,청진,NaN,NaN,41.7833,129.8167,43.0,NaN,NaN,NaN,NaN
3,12,2007-11-30,NaN,안면도(감),NaN,NaN,36.5333,126.3167,60.0,NaN,NaN,NaN,NaN
4,13,2012-01-01,NaN,고산센터,NaN,NaN,33.3000,126.1600,71.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7554,97810,2002-04-15,NaN,TUAL/DUMATUBUN,NaN,NaN,-5.6833,132.7500,NaN,NaN,NaN,NaN,NaN
7555,97876,2002-04-15,NaN,TANAH MERAH,NaN,NaN,-6.1000,140.3000,NaN,NaN,NaN,NaN,NaN
7556,97900,2002-04-15,NaN,SAUMLAKI/OLILIT,NaN,NaN,-7.9833,131.3000,NaN,NaN,NaN,NaN,NaN
7557,97980,2002-04-15,NaN,MERAUKE/MOPAH,NaN,NaN,-8.4667,140.3833,NaN,NaN,NaN,NaN,NaN
7558,98425,2002-04-15,NaN,마닐라,NaN,NaN,14.5833,120.9833,NaN,NaN,NaN,NaN,NaN

In [ ]:
# '지점' 및 '지점명' 열을 기준으로 그룹화하고 중복된 값 제거
df11 = df1.groupby(['지점', '지점명']).first().reset_index()
df12=df11[['지점','지점명']]
# 결과를 출력
print(df12)
#현재 운용중인 60개

     지점    지점명
0   116  관악(레)
1   309    판문점
2   326    용문산
3   376   광명노온
4   377   안양만안
5   427   김포장기
6   428   하남덕풍
7   433     부천
8   434     안양
9   437     광명
10  438     군포
11  441     김포
12  444     하남
13  445     의왕
14  446     남촌
15  450     주교
16  495     공도
17  499     중면
18  503    도라산
19  504     포천
20  505   가평조종
21  506   파주금촌
22  507     창수
23  514    대부도
24  515     운평
25  516     안성
26  531   가평북면
27  532    의정부
28  533     백사
29  534    장호원
30  538     신서
31  539   포천이동
32  540     고양
33  541    남양주
34  542     청평
35  544    전곡항
36  545     안산
37  546   경기광주
38  547     양동
39  548     여주
40  549     용인
41  550     오산
42  551     평택
43  565     시흥
44  567     적성
45  568     일동
46  569     구리
47  571     화성
48  573     청운
49  574     대신
50  575   용인이동
51  576     백암
52  589   고양고봉
53  590     과천
54  598     양주
55  599     광릉
56  652   연천청산
57  692     백학
58  966     풍도
59  967    도리도

In [ ]:
import pandas as pd

# df2와 df12 DataFrame이 이미 생성되어 있다고 가정합니다.

# '지점명' 열을 기준으로 left outer join 수행
merged_df = df12.merge(meta2, on='지점명', how='left')

print(merged_df)

     지점_x    지점명   지점_y         시작일         종료일  \
0     116  관악(레)    116  1993-11-10  2010-08-06
1     309    판문점    309  2020-09-17         NaN
2     326    용문산    326  2022-10-27         NaN
3     326    용문산    326  2015-07-13  2022-10-27
4     326    용문산    326  2012-05-24  2015-07-13
..    ...    ...    ...         ...         ...
194   966     풍도    966  2012-11-15  2017-12-22
195   966     풍도  22303  2021-08-27         NaN
196   966     풍도  22470  2012-12-17  2021-08-20
197   967    도리도    967  2017-12-22         NaN
198   967    도리도    967  2012-11-15  2017-12-22

                               지점주소              관리관서       위도        경도  \
0    경기도 과천시중앙로 관악산길(관악산기상레이더관측소)                 NaN  37.4433  126.9670
1                               NaN               NaN  37.9464  126.6866
2               경기도 양평군용문면 중원리464                 NaN  37.5455  127.6113
3               경기도 양평군용문면 중원리464                 NaN  37.5455  127.6113
4               경기도 양평군용문면 중원리464    이천지역기상서비스센터(203)  37.5455  127.6112
..                              ...               ...      ...       ...
194                             NaN        인천기상대(112)  37.1161  126.3856
195                             NaN               NaN  37.1583  126.4100
196                             NaN        인천기상대(112)  37.1167  126.3750
197                             NaN        인천기상대(112)  37.1189  126.6128
198                             NaN        인천기상대(112)  37.1189  126.6128

     노장해발고도(m)  기압계(관측장비지상높이(m))  기온계(관측장비지상높이(m))  풍속계(관측장비지상높이(m))  \
0       634.00               NaN               NaN               NaN
1        25.00               NaN               NaN               0.5
2       191.01               NaN               NaN               NaN
3       191.01               NaN               NaN               NaN
4       190.20               NaN               NaN               NaN
..         ...               ...               ...               ...
194      38.00               NaN               NaN               NaN
195        NaN               NaN               NaN               NaN
196        NaN               NaN               NaN               NaN
197      70.00               NaN               NaN               NaN
198      70.00               NaN               NaN               NaN

     강우계(관측장비지상높이(m))
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
..                ...
194               NaN
195               NaN
196               NaN
197               NaN
198               NaN

[199 rows x 14 columns]

In [ ]:
import pandas as pd

# Assuming merged_df is your DataFrame
# Filter rows where '종료일' is NaN
filtered_merged_df = merged_df[merged_df['종료일'].isna()]

# The 'filtered_merged_df' DataFrame will contain only rows where '종료일' is NaN.
print(filtered_merged_df)

     지점_x   지점명   지점_y         시작일  종료일                              지점주소  \
1     309   판문점    309  2020-09-17  NaN                               NaN
2     326   용문산    326  2022-10-27  NaN               경기도 양평군용문면 중원리464
6     376  광명노온    376  2021-07-01  NaN                               NaN
7     377  안양만안    377  2021-12-31  NaN                               NaN
8     427  김포장기    427  2020-10-23  NaN         경기도 김포시장기동 1539(한강중앙공원)
..    ...   ...    ...         ...  ...                               ...
188   652  연천청산    652  2020-10-23  NaN     경기도 연천군청산면 초성리 376-1 육군 제28사단
190   692    백학    692  2015-07-13  NaN  경기도 연천군백학면 두일리 66 육군 제25사단 수색대대
193   966    풍도    966  2017-12-22  NaN                               NaN
195   966    풍도  22303  2021-08-27  NaN                               NaN
197   967   도리도    967  2017-12-22  NaN                               NaN

           관리관서       위도        경도  노장해발고도(m)  기압계(관측장비지상높이(m))  \
1           NaN  37.9464  126.6866      25.00               NaN
2           NaN  37.5455  127.6113     191.01               NaN
6           NaN  37.4474  126.8590      68.57               NaN
7           NaN  37.3952  126.8919      28.00               NaN
8           NaN  37.6428  126.6734      10.54               NaN
..          ...      ...       ...        ...               ...
188         NaN  37.9900  127.0727      38.29               NaN
190         NaN  38.0404  126.9245      33.24               NaN
193  인천기상대(112)  37.1161  126.3856      38.00               NaN
195         NaN  37.1583  126.4100        NaN               NaN
197  인천기상대(112)  37.1189  126.6128      70.00               NaN

     기온계(관측장비지상높이(m))  풍속계(관측장비지상높이(m))  강우계(관측장비지상높이(m))
1                 NaN               0.5               NaN
2                 NaN               NaN               NaN
6                 NaN               NaN               NaN
7                 NaN               NaN               NaN
8                 NaN               NaN               NaN
..                ...               ...               ...
188               NaN               NaN               NaN
190               NaN               NaN               NaN
193               NaN               NaN               NaN
195               NaN               NaN               NaN
197               NaN               NaN               NaN

[71 rows x 14 columns]

In [ ]:
filtered_merged_df2 = filtered_merged_df[filtered_merged_df['지점_x']==(filtered_merged_df['지점_y'])]

# 결과를 출력
print(filtered_merged_df2)

     지점_x   지점명  지점_y         시작일  종료일  \
1     309   판문점   309  2020-09-17  NaN
2     326   용문산   326  2022-10-27  NaN
6     376  광명노온   376  2021-07-01  NaN
7     377  안양만안   377  2021-12-31  NaN
8     427  김포장기   427  2020-10-23  NaN
10    428  하남덕풍   428  2020-10-23  NaN
12    433    부천   433  2021-05-04  NaN
14    434    안양   434  2003-08-13  NaN
16    437    광명   437  2021-05-04  NaN
19    438    군포   438  2021-05-04  NaN
21    441    김포   441  2021-01-14  NaN
23    444    하남   444  2021-05-04  NaN
25    445    의왕   445  2021-05-04  NaN
27    446    남촌   446  2021-05-04  NaN
29    450    주교   450  2021-05-04  NaN
31    495    공도   495  2018-10-25  NaN
32    499    중면   499  2020-10-15  NaN
36    503   도라산   503  2015-07-13  NaN
40    504    포천   504  2021-09-10  NaN
47    505  가평조종   505  2020-04-21  NaN
50    506  파주금촌   506  2021-07-15  NaN
52    507    창수   507  2021-10-15  NaN
57    514   대부도   514  2022-10-01  NaN
61    515    운평   515  2012-11-30  NaN
63    516    안성   516  2017-08-25  NaN
67    531  가평북면   531  2017-08-25  NaN
69    532   의정부   532  2015-07-13  NaN
73    533    백사   533  2020-07-11  NaN
74    534   장호원   534  2017-08-25  NaN
78    538    신서   538  2015-07-13  NaN
80    539  포천이동   539  2020-10-13  NaN
82    540    고양   540  2015-07-13  NaN
91    541   남양주   541  2020-10-23  NaN
99    542    청평   542  1992-11-01  NaN
101   544   전곡항   544  2011-11-11  NaN
102   545    안산   545  2015-10-14  NaN
104   546  경기광주   546  2016-08-01  NaN
105   547    양동   547  2015-07-13  NaN
109   548    여주   548  2017-08-25  NaN
114   549    용인   549  2020-10-23  NaN
119   550    오산   550  2022-11-26  NaN
127   551    평택   551  2010-11-01  NaN
130   565    시흥   565  2021-07-22  NaN
133   567    적성   567  2020-10-17  NaN
139   568    일동   568  2020-10-23  NaN
146   569    구리   569  2022-09-29  NaN
152   571    화성   571  2021-09-16  NaN
155   573    청운   573  2021-07-14  NaN
159   574    대신   574  2020-10-09  NaN
163   575  용인이동   575  2021-10-15  NaN
167   576    백암   576  2020-10-08  NaN
172   589  고양고봉   589  2022-09-27  NaN
174   590    과천   590  2010-12-14  NaN
180   598    양주   598  2021-09-15  NaN
184   599    광릉   599  2021-07-13  NaN
188   652  연천청산   652  2020-10-23  NaN
190   692    백학   692  2015-07-13  NaN
193   966    풍도   966  2017-12-22  NaN
197   967   도리도   967  2017-12-22  NaN

                                            지점주소              관리관서       위도  \
1                                            NaN               NaN  37.9464
2                            경기도 양평군용문면 중원리464                 NaN  37.5455
6                                            NaN               NaN  37.4474
7                                            NaN               NaN  37.3952
8                      경기도 김포시장기동 1539(한강중앙공원)                 NaN  37.6428
10                 경기도 하남시덕풍동 726-11(풍산근린3호공원)                 NaN  37.5512
12                                           NaN        인천기상대(112)  37.5006
14                                           NaN               NaN  37.3944
16                                           NaN        인천기상대(112)  37.4787
19                                           NaN               NaN  37.3615
21                                           NaN        인천기상대(112)  37.6076
23                                           NaN  이천지역기상서비스센터(203)  37.5379
25                                           NaN               NaN  37.3445
27                                           NaN               NaN  37.1403
29                                           NaN         파주기상대(99)  37.6582
31              경기도 안성시공도읍 불당길40-68(불당 하수종말처리장)                NaN  36.9806
32              경기도 연천군중면 삼곶리 260 육군 제28사단 81연대                NaN  38.1361
36                       경기도 파주시장단면 도라산리18도라대대                 NaN  37.9080
40                     경기도 포천시자작동 264-1육군15항공단                 NaN  37.8704
47                      경기도 가평군하면 현리209 가평 하면정수장               NaN  37.8244
50                   경기도 파주시금촌2동 1017(파주시 주말농장)                NaN  37.7482
52                 경기도 포천시창수면 고소성리123 육군 제3985부대               NaN  38.0248
57                        경기도 안산시단원구 대부남동299-3          인천기상대(112)  37.2377
61                  경기도 화성시우정읍 평밭길(운평리601-6번지)                 NaN  37.0845
63                      경기도 안성시옥산동 365번지알미산공원내                 NaN  37.0037
67                           경기도 가평군북면 소법리 465-2               NaN  37.8981
69            경기도 의정부시 시민로 368-10용현배수지 궁도장 (용현동)               NaN  37.7348
73                         경기도 이천시백사면 조읍리 251-10               NaN  37.3278
74   경기도 이천시장호원읍 서동대로8759번길 97-103 이천시복숭아연구소시험포장               NaN  37.1210
78                 경기도 연천군신서면 도신4리164-1 소득자원연구소                NaN  38.1725
80                    경기도 포천시이동면 장암리264-1 이동비행장                NaN  38.0242
82                     경기도 고양시덕양구 동산동300-1 60사단                NaN  37.6373
91               경기도 남양주시진건읍 배양리 922-3(진건 푸른물센터)               NaN  37.6341
99                        경기도 가평군청평면 대성리393-12                 NaN  37.6841
101        경기도 화성시서신면 전곡항로14번길(제2819부대 2대대 전곡중대)               NaN  37.1857
102                  경기도 안산시상록구 해안로870(농어촌연구원)                 NaN  37.2810
104          경기도 광주시회안대로 1061-59한국수자원공사 광주수도관리단                NaN  37.4353
105                    경기도 양평군양동면 쌍학리865-4 양수장 내               NaN  37.4159
109            경기도 여주시점봉동 429-29여주시 상수도사업소 점봉배수지               NaN  37.2688
114             경기도 용인시처인구 포곡읍둔전리 사서함 1호(육군55사단)               NaN  37.2701
119          경기도 오산시 청학로 211금암동 236  물향기수목원(수청동)               NaN  37.1693
127              경기도 평택시합정동 배미2길(평택시공설운동장 부지 야산)               NaN  36.9877
130               경기도 시흥시장곡동 724-32 시흥시갯골생태공원내                 NaN  37.3915
133            경기도 파주시적성면 구읍리 사서함 95-16  제8567부대               NaN  37.9533
139                        경기도 포천시일동면 기산리106-1                 NaN  37.9588
146                       경기도 구리시토평동 48-99토평IC                 NaN  37.5822
152                  경기도 화성시남양로 621(2819부대2대대)                 NaN  37.1953
155                          경기도 양평군청운면 용두리595                 NaN  37.5582
159                        경기도 여주시대신면 초현리520-3                 NaN  37.3694
163          경기도 용인시처인구 이동면어비리 1093-1(이동저수지관리소)                NaN  37.1058
167                       경기도 용인시처인구 백암면용천리 산27                NaN  37.1297
172                 경기도 고양시일산동구 성석동산69-2 5895부대                NaN  37.7024
174                경기도 과천시과천시 상하벌로110(국립과천과학관)                 NaN  37.4403
180               경기도 양주시광적면 석우리 산 6번지 제 8030부대                NaN  37.8312
184             경기도 포천시소흘읍 직동리 642-4  산림기술경영연구소                NaN  37.7617
188                경기도 연천군청산면 초성리 376-1 육군 제28사단               NaN  37.9900
190             경기도 연천군백학면 두일리 66 육군 제25사단 수색대대                NaN  38.0404
193                                          NaN        인천기상대(112)  37.1161
197                                          NaN        인천기상대(112)  37.1189

           경도  노장해발고도(m)  기압계(관측장비지상높이(m))  기온계(관측장비지상높이(m))  \
1    126.6866      25.00               NaN               NaN
2    127.6113     191.01               NaN               NaN
6    126.8590      68.57               NaN               NaN
7    126.8919      28.00               NaN               NaN
8    126.6734      10.54               NaN               NaN
10   127.2128      23.73               NaN               NaN
12   126.7636      15.67               NaN               NaN
14   126.9569      77.92               NaN               NaN
16   126.8653      52.69               NaN               NaN
19   126.9353      84.71               NaN               NaN
21   126.7624      28.00               NaN               NaN
23   127.2137      27.68               NaN               NaN
25   126.9688      80.40               NaN               NaN
27   127.0637      17.48               NaN               NaN
29   126.8312      45.34               NaN               NaN
31   127.1625      13.00               NaN               NaN
32   127.0235      53.70               NaN               NaN
36   126.7119      18.29               NaN               NaN
40   127.1807     105.14               NaN               NaN
47   127.3454     170.45               NaN               NaN
50   126.7769      12.88               NaN               NaN
52   127.1436      76.06               NaN               NaN
57   126.5787      10.00               NaN               NaN
61   126.7739      10.47               NaN               NaN
63   127.2502      23.92               NaN               NaN
67   127.5522     109.66               NaN               NaN
69   127.0735      89.49               NaN               NaN
73   127.4807      82.00               NaN               NaN
74   127.6106      88.20               NaN               NaN
78   127.1030      83.25               NaN               NaN
80   127.3657     137.74               NaN               NaN
82   126.8920      44.71               NaN               NaN
91   127.1506      25.36               NaN               NaN
99   127.3802      41.96               NaN               NaN
101  126.6544      10.96               NaN               NaN
102  126.8385       5.92               NaN               NaN
104  127.2592     122.61               NaN               NaN
105  127.7549     108.62               NaN               NaN
109  127.6396     118.56               NaN               NaN
114  127.2218      83.00               NaN               NaN
119  127.0527      34.89               NaN               NaN
127  127.1088      27.14               NaN               NaN
130  126.7780       5.77               NaN               NaN
133  126.9318      71.25               NaN               NaN
139  127.3135     142.00               NaN               NaN
146  127.1570      27.15               NaN               NaN
152  126.8209      45.39               NaN               NaN
155  127.7135     120.49               NaN               NaN
159  127.5871      36.85               NaN               NaN
163  127.1877      51.18               NaN               NaN
167  127.3663     111.46               NaN               NaN
172  126.7903      59.07               NaN               NaN
174  127.0025      46.60               NaN               NaN
180  126.9905      87.76               NaN               NaN
184  127.1698     105.82               NaN               NaN
188  127.0727      38.29               NaN               NaN
190  126.9245      33.24               NaN               NaN
193  126.3856      38.00               NaN               NaN
197  126.6128      70.00               NaN               NaN

     풍속계(관측장비지상높이(m))  강우계(관측장비지상높이(m))
1                 0.5               NaN
2                 NaN               NaN
6                 NaN               NaN
7                 NaN               NaN
8                 NaN               NaN
10                NaN               NaN
12                NaN               NaN
14                NaN               NaN
16                NaN               NaN
19                NaN               NaN
21                NaN               NaN
23                NaN               NaN
25                NaN               NaN
27                NaN               NaN
29                NaN               NaN
31                NaN               NaN
32                NaN               NaN
36                NaN               NaN
40                NaN               NaN
47                NaN               NaN
50                NaN               NaN
52                NaN               NaN
57                NaN               NaN
61                NaN               NaN
63                NaN               NaN
67                NaN               NaN
69                NaN               NaN
73                NaN               NaN
74                NaN               NaN
78                NaN               NaN
80                NaN               NaN
82                NaN               NaN
91                NaN               NaN
99                NaN               NaN
101               NaN               NaN
102               NaN               NaN
104               NaN               NaN
105               NaN               NaN
109               NaN               NaN
114               NaN               NaN
119               NaN               NaN
127               NaN               NaN
130               NaN               NaN
133               NaN               NaN
139               NaN               NaN
146               NaN               NaN
152               NaN               NaN
155               NaN               NaN
159               NaN               NaN
163               NaN               NaN
167               NaN               NaN
172               NaN               NaN
174               NaN               NaN
180               NaN               NaN
184               NaN               NaN
188               NaN               NaN
190               NaN               NaN
193               NaN               NaN
197               NaN               NaN

In [ ]:
row_count = len(filtered_merged_df2)
print("Number of rows in filtered_merged_df2:", row_count)
#59개로 한개가 줄음
#meta 데이터 상에서 종료되었다는 관악(레) 관측소가 종료되지 않음을 확인
final_df=filtered_merged_df2

Number of rows in filtered_merged_df2: 59

In [ ]:
final_df2 = final_df[['지점_x', '지점명', '지점주소', '위도', '경도']]
print(final_df2)

     지점_x   지점명                                         지점주소       위도  \
1     309   판문점                                          NaN  37.9464
2     326   용문산                          경기도 양평군용문면 중원리464    37.5455
6     376  광명노온                                          NaN  37.4474
7     377  안양만안                                          NaN  37.3952
8     427  김포장기                    경기도 김포시장기동 1539(한강중앙공원)    37.6428
10    428  하남덕풍                경기도 하남시덕풍동 726-11(풍산근린3호공원)    37.5512
12    433    부천                                          NaN  37.5006
14    434    안양                                          NaN  37.3944
16    437    광명                                          NaN  37.4787
19    438    군포                                          NaN  37.3615
21    441    김포                                          NaN  37.6076
23    444    하남                                          NaN  37.5379
25    445    의왕                                          NaN  37.3445
27    446    남촌                                          NaN  37.1403
29    450    주교                                          NaN  37.6582
31    495    공도             경기도 안성시공도읍 불당길40-68(불당 하수종말처리장)   36.9806
32    499    중면             경기도 연천군중면 삼곶리 260 육군 제28사단 81연대   38.1361
36    503   도라산                      경기도 파주시장단면 도라산리18도라대대    37.9080
40    504    포천                    경기도 포천시자작동 264-1육군15항공단    37.8704
47    505  가평조종                     경기도 가평군하면 현리209 가평 하면정수장  37.8244
50    506  파주금촌                  경기도 파주시금촌2동 1017(파주시 주말농장)   37.7482
52    507    창수                경기도 포천시창수면 고소성리123 육군 제3985부대  38.0248
57    514   대부도                       경기도 안산시단원구 대부남동299-3    37.2377
61    515    운평                 경기도 화성시우정읍 평밭길(운평리601-6번지)    37.0845
63    516    안성                     경기도 안성시옥산동 365번지알미산공원내    37.0037
67    531  가평북면                          경기도 가평군북면 소법리 465-2  37.8981
69    532   의정부           경기도 의정부시 시민로 368-10용현배수지 궁도장 (용현동)  37.7348
73    533    백사                        경기도 이천시백사면 조읍리 251-10  37.3278
74    534   장호원  경기도 이천시장호원읍 서동대로8759번길 97-103 이천시복숭아연구소시험포장  37.1210
78    538    신서                경기도 연천군신서면 도신4리164-1 소득자원연구소   38.1725
80    539  포천이동                   경기도 포천시이동면 장암리264-1 이동비행장   38.0242
82    540    고양                    경기도 고양시덕양구 동산동300-1 60사단   37.6373
91    541   남양주              경기도 남양주시진건읍 배양리 922-3(진건 푸른물센터)  37.6341
99    542    청평                       경기도 가평군청평면 대성리393-12    37.6841
101   544   전곡항        경기도 화성시서신면 전곡항로14번길(제2819부대 2대대 전곡중대)  37.1857
102   545    안산                  경기도 안산시상록구 해안로870(농어촌연구원)    37.2810
104   546  경기광주          경기도 광주시회안대로 1061-59한국수자원공사 광주수도관리단   37.4353
105   547    양동                    경기도 양평군양동면 쌍학리865-4 양수장 내  37.4159
109   548    여주            경기도 여주시점봉동 429-29여주시 상수도사업소 점봉배수지  37.2688
114   549    용인             경기도 용인시처인구 포곡읍둔전리 사서함 1호(육군55사단)  37.2701
119   550    오산          경기도 오산시 청학로 211금암동 236  물향기수목원(수청동)  37.1693
127   551    평택              경기도 평택시합정동 배미2길(평택시공설운동장 부지 야산)  36.9877
130   565    시흥               경기도 시흥시장곡동 724-32 시흥시갯골생태공원내    37.3915
133   567    적성            경기도 파주시적성면 구읍리 사서함 95-16  제8567부대  37.9533
139   568    일동                        경기도 포천시일동면 기산리106-1    37.9588
146   569    구리                       경기도 구리시토평동 48-99토평IC    37.5822
152   571    화성                  경기도 화성시남양로 621(2819부대2대대)    37.1953
155   573    청운                          경기도 양평군청운면 용두리595    37.5582
159   574    대신                        경기도 여주시대신면 초현리520-3    37.3694
163   575  용인이동          경기도 용인시처인구 이동면어비리 1093-1(이동저수지관리소)   37.1058
167   576    백암                       경기도 용인시처인구 백암면용천리 산27   37.1297
172   589  고양고봉                 경기도 고양시일산동구 성석동산69-2 5895부대   37.7024
174   590    과천                경기도 과천시과천시 상하벌로110(국립과천과학관)    37.4403
180   598    양주               경기도 양주시광적면 석우리 산 6번지 제 8030부대   37.8312
184   599    광릉             경기도 포천시소흘읍 직동리 642-4  산림기술경영연구소   37.7617
188   652  연천청산                경기도 연천군청산면 초성리 376-1 육군 제28사단  37.9900
190   692    백학             경기도 연천군백학면 두일리 66 육군 제25사단 수색대대   38.0404
193   966    풍도                                          NaN  37.1161
197   967   도리도                                          NaN  37.1189

           경도
1    126.6866
2    127.6113
6    126.8590
7    126.8919
8    126.6734
10   127.2128
12   126.7636
14   126.9569
16   126.8653
19   126.9353
21   126.7624
23   127.2137
25   126.9688
27   127.0637
29   126.8312
31   127.1625
32   127.0235
36   126.7119
40   127.1807
47   127.3454
50   126.7769
52   127.1436
57   126.5787
61   126.7739
63   127.2502
67   127.5522
69   127.0735
73   127.4807
74   127.6106
78   127.1030
80   127.3657
82   126.8920
91   127.1506
99   127.3802
101  126.6544
102  126.8385
104  127.2592
105  127.7549
109  127.6396
114  127.2218
119  127.0527
127  127.1088
130  126.7780
133  126.9318
139  127.3135
146  127.1570
152  126.8209
155  127.7135
159  127.5871
163  127.1877
167  127.3663
172  126.7903
174  127.0025
180  126.9905
184  127.1698
188  127.0727
190  126.9245
193  126.3856
197  126.6128

In [ ]:
new_data = {
    '지점_x': 116,
    '지점명': '관악(레)',
    '지점주소': '경기도 과천시 중앙로 관악산길(관악산기상레이더관측소)',
    '위도': 37.44526,
    '경도': 126.96402
}

final_df3 = final_df2.append(new_data, ignore_index=True)
#관악(레) 관측소 추가

<ipython-input-100-0b7bc94524a6>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df3 = final_df2.append(new_data, ignore_index=True)

In [ ]:
print(final_df3)
#60개 운용중인 관측소의 모든 위경도

    지점_x    지점명                                         지점주소        위도  \
0    309    판문점                                          NaN  37.94640
1    326    용문산                          경기도 양평군용문면 중원리464    37.54550
2    376   광명노온                                          NaN  37.44740
3    377   안양만안                                          NaN  37.39520
4    427   김포장기                    경기도 김포시장기동 1539(한강중앙공원)    37.64280
5    428   하남덕풍                경기도 하남시덕풍동 726-11(풍산근린3호공원)    37.55120
6    433     부천                                          NaN  37.50060
7    434     안양                                          NaN  37.39440
8    437     광명                                          NaN  37.47870
9    438     군포                                          NaN  37.36150
10   441     김포                                          NaN  37.60760
11   444     하남                                          NaN  37.53790
12   445     의왕                                          NaN  37.34450
13   446     남촌                                          NaN  37.14030
14   450     주교                                          NaN  37.65820
15   495     공도             경기도 안성시공도읍 불당길40-68(불당 하수종말처리장)   36.98060
16   499     중면             경기도 연천군중면 삼곶리 260 육군 제28사단 81연대   38.13610
17   503    도라산                      경기도 파주시장단면 도라산리18도라대대    37.90800
18   504     포천                    경기도 포천시자작동 264-1육군15항공단    37.87040
19   505   가평조종                     경기도 가평군하면 현리209 가평 하면정수장  37.82440
20   506   파주금촌                  경기도 파주시금촌2동 1017(파주시 주말농장)   37.74820
21   507     창수                경기도 포천시창수면 고소성리123 육군 제3985부대  38.02480
22   514    대부도                       경기도 안산시단원구 대부남동299-3    37.23770
23   515     운평                 경기도 화성시우정읍 평밭길(운평리601-6번지)    37.08450
24   516     안성                     경기도 안성시옥산동 365번지알미산공원내    37.00370
25   531   가평북면                          경기도 가평군북면 소법리 465-2  37.89810
26   532    의정부           경기도 의정부시 시민로 368-10용현배수지 궁도장 (용현동)  37.73480
27   533     백사                        경기도 이천시백사면 조읍리 251-10  37.32780
28   534    장호원  경기도 이천시장호원읍 서동대로8759번길 97-103 이천시복숭아연구소시험포장  37.12100
29   538     신서                경기도 연천군신서면 도신4리164-1 소득자원연구소   38.17250
30   539   포천이동                   경기도 포천시이동면 장암리264-1 이동비행장   38.02420
31   540     고양                    경기도 고양시덕양구 동산동300-1 60사단   37.63730
32   541    남양주              경기도 남양주시진건읍 배양리 922-3(진건 푸른물센터)  37.63410
33   542     청평                       경기도 가평군청평면 대성리393-12    37.68410
34   544    전곡항        경기도 화성시서신면 전곡항로14번길(제2819부대 2대대 전곡중대)  37.18570
35   545     안산                  경기도 안산시상록구 해안로870(농어촌연구원)    37.28100
36   546   경기광주          경기도 광주시회안대로 1061-59한국수자원공사 광주수도관리단   37.43530
37   547     양동                    경기도 양평군양동면 쌍학리865-4 양수장 내  37.41590
38   548     여주            경기도 여주시점봉동 429-29여주시 상수도사업소 점봉배수지  37.26880
39   549     용인             경기도 용인시처인구 포곡읍둔전리 사서함 1호(육군55사단)  37.27010
40   550     오산          경기도 오산시 청학로 211금암동 236  물향기수목원(수청동)  37.16930
41   551     평택              경기도 평택시합정동 배미2길(평택시공설운동장 부지 야산)  36.98770
42   565     시흥               경기도 시흥시장곡동 724-32 시흥시갯골생태공원내    37.39150
43   567     적성            경기도 파주시적성면 구읍리 사서함 95-16  제8567부대  37.95330
44   568     일동                        경기도 포천시일동면 기산리106-1    37.95880
45   569     구리                       경기도 구리시토평동 48-99토평IC    37.58220
46   571     화성                  경기도 화성시남양로 621(2819부대2대대)    37.19530
47   573     청운                          경기도 양평군청운면 용두리595    37.55820
48   574     대신                        경기도 여주시대신면 초현리520-3    37.36940
49   575   용인이동          경기도 용인시처인구 이동면어비리 1093-1(이동저수지관리소)   37.10580
50   576     백암                       경기도 용인시처인구 백암면용천리 산27   37.12970
51   589   고양고봉                 경기도 고양시일산동구 성석동산69-2 5895부대   37.70240
52   590     과천                경기도 과천시과천시 상하벌로110(국립과천과학관)    37.44030
53   598     양주               경기도 양주시광적면 석우리 산 6번지 제 8030부대   37.83120
54   599     광릉             경기도 포천시소흘읍 직동리 642-4  산림기술경영연구소   37.76170
55   652   연천청산                경기도 연천군청산면 초성리 376-1 육군 제28사단  37.99000
56   692     백학             경기도 연천군백학면 두일리 66 육군 제25사단 수색대대   38.04040
57   966     풍도                                          NaN  37.11610
58   967    도리도                                          NaN  37.11890
59   116  관악(레)                경기도 과천시 중앙로 관악산길(관악산기상레이더관측소)  37.44526

           경도
0   126.68660
1   127.61130
2   126.85900
3   126.89190
4   126.67340
5   127.21280
6   126.76360
7   126.95690
8   126.86530
9   126.93530
10  126.76240
11  127.21370
12  126.96880
13  127.06370
14  126.83120
15  127.16250
16  127.02350
17  126.71190
18  127.18070
19  127.34540
20  126.77690
21  127.14360
22  126.57870
23  126.77390
24  127.25020
25  127.55220
26  127.07350
27  127.48070
28  127.61060
29  127.10300
30  127.36570
31  126.89200
32  127.15060
33  127.38020
34  126.65440
35  126.83850
36  127.25920
37  127.75490
38  127.63960
39  127.22180
40  127.05270
41  127.10880
42  126.77800
43  126.93180
44  127.31350
45  127.15700
46  126.82090
47  127.71350
48  127.58710
49  127.18770
50  127.36630
51  126.79030
52  127.00250
53  126.99050
54  127.16980
55  127.07270
56  126.92450
57  126.38560
58  126.61280
59  126.96402

In [ ]:
final_df4=final_df3.rename(columns={
    '지점_x': 'AWS_관측지점',
    '지점명': 'AWS_지점명',
    '지점주소': 'AWS_지점주소',
    '위도': 'AWS_위도',
    '경도': 'AWS_경도'
})

In [ ]:
from google.colab import files
# df4를 적절한 파일 이름으로 CSV 파일로 저장
final_df4.to_csv('AWS관측지점위경도_ver1.csv', index=False, encoding='euc-kr')
# 파일을 다운로드
files.download('AWS관측지점위경도_ver1.csv')